# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/fef8f90b-499b-4089-8eea-c4ecbf1cc8a8";
    fsType = "btrfs";
    options = [ "noatime,ssd,discard=async,subvol=@" ];
  };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/a6911461-bfed-4c54-bff4-f92b98fc8a90";

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/fef8f90b-499b-4089-8eea-c4ecbf1cc8a8";
    fsType = "btrfs";
    options = [ "noatime,ssd,discard=async,subvol=@home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/fef8f90b-499b-4089-8eea-c4ecbf1cc8a8";
    fsType = "btrfs";
    options = [ "noatime,ssd,discard=async,subvol=@nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/36DB-E3AD";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
