# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "ahci"
    "xhci_pci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/65487017-8d84-4a7d-ba17-a0e8536ff39a";
    fsType = "btrfs";
    options = ["noatime,ssd,discard=async,subvol=@"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/65487017-8d84-4a7d-ba17-a0e8536ff39a";
    fsType = "btrfs";
    options = ["noatime,ssd,discard=async,subvol=@home"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/65487017-8d84-4a7d-ba17-a0e8536ff39a";
    fsType = "btrfs";
    options = ["noatime,ssd,discard=async,subvol=@nix"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4638-FB30";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/mnt/windows-kunzoz" = {
    device = "/dev/disk/by-uuid/DC2C38A72C387F18";
    fsType = "ntfs3";
    options = [
      "rw"
      "nosuid"
      "nodev"
      "relatime"
      "uid=1000"
      "gid=100"
      "iocharset=utf8"
      # don't fail boot if the drives fail to mount
      "nofail"
      # continue boot after 10s
      "x-systemd.mount-timeout=10"
    ];
  };

  fileSystems."/mnt/windows-dad" = {
    device = "/dev/disk/by-uuid/84B25357B2534CB4";
    fsType = "ntfs3";
    options = [
      "rw"
      "nosuid"
      "nodev"
      "relatime"
      "uid=1000"
      "gid=100"
      "iocharset=utf8"
      # don't fail boot if the drives fail to mount
      "nofail"
      # continue boot after 10s
      "x-systemd.mount-timeout=10"
    ];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp14s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp15s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
